### ISSUE TITLE
Add feature section in README.md

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-utils#2]
We have to add Feature section in readme into file 

I want contributors help to add this 
Join discord link for this: 

[Join Discord](https://discord.gg/qNeQBF2Q)

**Comment by RahulJOD** [comment]
i want to contribute

**Comment by bharat-dussa** [comment]
@RahulJOD  yes you can pick this up

**Comment by bharat-dussa** [comment]
Closing issue is resolved
