### ISSUE TITLE
Add Contributing guide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-utils#5]
We have to add usage section in readme into file

I want contributors help to add this
Join discord link for this:

[Join Discord](https://discord.gg/qNeQBF2Q)

**Comment by prachidoddi** [comment]
@bharat-dussa  ,i want to contribute in this

**Comment by vigneshbirru** [comment]
i want to contribution on this issues

**Comment by VamshiAdep** [comment]
@bharat-dussa i want to contribute to this task please assign

**Comment by vigneshbirru** [comment]
i have  added contain as per issue  #5

**Comment by bharat-dussa** [comment]
Closing as issue has resolved
